#===============================================================================
# BOT Configuration file
#===============================================================================

#===============================================================================
# REPORT
#===============================================================================
sysInfo: True
netInfo: True
sysStat: True
netStat: True
sampling:
  amount: 60
  unit: "SECONDS"

#===============================================================================
# C&C RESOURCES
#===============================================================================
initResource: !templateString "${PWD}/cc/botinit.json"
cmdResource: !templateString "${PWD}/cc/botcmd.json"
logResource: !templateString "${PWD}/cc/botlog.json"