#===============================================================================
# BOT Configuration file
#===============================================================================

#===============================================================================
# REPORT
#===============================================================================
sysInfo: True
netInfo: True
sysStat: False
netStat: False
sampling:
  amount: 3
  unit: "MINUTES"

#===============================================================================
# C&C RESOURCES
#===============================================================================
initResource: !templateString "${PWD}/cc/botinit.json"
cmdResource: !templateString "${PWD}/cc/botcmd.json"
logResource: !templateString "${PWD}/cc/botlog.json"