#===============================================================================
# BOT Configuration file
#===============================================================================

#===============================================================================
# REPORT
#===============================================================================
cnfInfo: True
tgtInfo: True
sysInfo: True
netInfo: True

#===============================================================================
# COMMAND&CONTROL
#===============================================================================
controllers:
  - init: data/samples/controllers/1/botinit.json
    command: data/samples/controllers/1/botcmd.json
    log: data/samples/controllers/1/botlog.json
polling: 10-10:SECONDS
reconnections: 3
reconnectionWait: 10-10:SECONDS
proxy: null
userAgent: null