#===============================================================================
# BOT Configuration file
#===============================================================================

#===============================================================================
# REPORT
#===============================================================================
cnfInfo: True
tgtInfo: True
sysInfo: True
netInfo: True

#===============================================================================
# COMMAND&CONTROL
#===============================================================================
controllers:
  - init: data/samples/controllers/invalid/botinit.json
    command: data/samples/controllers/invalid/botcmd.json
    log: data/samples/controllers/invalid/botlog.json
  - init: data/samples/controllers/1/botinit.json
    command: data/samples/controllers/1/botcmd.json
    log: data/samples/controllers/1/botlog.json
polling: 90-120:SECONDS
reconnections: 3
reconnectionWait: 2-5:SECONDS
proxy: none
userAgent: MyAwesomeBot
