#===============================================================================
# BOT Configuration file
#===============================================================================

#===============================================================================
# REPORT
#===============================================================================
sysInfo: True
netInfo: True

#===============================================================================
# COMMAND&CONTROL
#===============================================================================
controllers:
  - init: data/controller/1/botinit.json
    command: data/controller/1/botcmd.json
    log: data/controller/1/botlog.json
polling: 10-10:SECONDS
reconnections: 3
reconnectionWait: 10-10:SECONDS
proxy: null
userAgent: null