#===============================================================================
# BOT Configuration file
#===============================================================================

#===============================================================================
# REPORT
#===============================================================================
sysInfo: True
netInfo: True
sysStat: True
netStat: True
sampling: "1:MINUTES"

#===============================================================================
# C&C RESOURCES
#===============================================================================
initResource: "${PWD}/cc/botinit.json"
cmdResource: "${PWD}/cc/botcmd.json"
logResource: "${PWD}/cc/botlog.json"