#===============================================================================
# BOT Configuration file
#===============================================================================

cnfInfo: true
tgtInfo: true
sysInfo: true
netInfo: false
polling: "3-5:SECONDS"
reconnections: 3
reconnectionWait: "2-5:SECONDS"
proxy: "none"
sleep: "* * * ? * SAT,SUN"
authentication:
  User-Agent: MyAwesomeBot
controllers:
  - init: http://localhost:4000/init
    command: http://localhost:4000/command
    log: http://localhost:4000/report
  - init: http://localhost:3000/init
    command: http://localhost:3000/command
    log: http://localhost:3000/report
  - init: data/samples/controllers/1/init.json
    command: data/samples/controllers/1/command.json
    log: data/samples/controllers/1/report.json