#===============================================================================
# BOT Configuration file
#===============================================================================

cnfInfo: true
tgtInfo: true
sysInfo: true
netInfo: true
polling: "10-10:SECONDS"
reconnections: 3
reconnectionWait: "10-10:SECONDS"
proxy: "none"
sleep: null
authentication: {}
controllers:
  - init: data/samples/controllers/1/botinit.json
    command: data/samples/controllers/1/botcmd.json
    log: data/samples/controllers/1/botlog.json