sysInfo: True
netInfo: True
sysStat: True
netStat: True
sysStatFreq: 5
netStatFreq: 5
initResource: "com/acmutv/botnet/botinit.txt"
cmdResource: "com/acmutv/botnet/botcmd.txt"
logResource: "com/acmutv/botnet/botlog.txt"
maxTime: 60
debug: True