#===============================================================================
# BOT Configuration file
#===============================================================================

#===============================================================================
# REPORT
#===============================================================================
#sysInfo: True
#netInfo: True
#sysStat: True
#netStat: True
#sampling: 1:MINUTES

#===============================================================================
# C&C
#===============================================================================
controllers:
  - init: "${RES}/cc/botinit.json"
    command: "${RES}/cc/botcmd.json"
    log: "${RES}/cc/botlog.json"
polling: 10-10:SECONDS