#===============================================================================
# BOT Configuration file
#===============================================================================

#===============================================================================
# REPORT
#===============================================================================
#sysInfo: True
#netInfo: True
#sysStat: True
#netStat: True
#sampling: 1:MINUTES

#===============================================================================
# C&C RESOURCES
#===============================================================================
#initResource: "${RES}/cc/botinit.json"
#cmdResource: "${RES}/cc/botcmd.json"
#logResource: "${RES}/cc/botlog.json"
#polling: 10-10:SECONDS