#===============================================================================
# BOT Configuration file
#===============================================================================

#===============================================================================
# REPORT
#===============================================================================
#sysInfo: True
#netInfo: True

#===============================================================================
# COMMAND&CONTROL
#===============================================================================
#controllers:
#  - init: ${PWD}/data/controller/botinit.json
#    command: ${PWD}/data/controller/botcmd.json
#    log: ${PWD}/data/controller/botlog.json
#polling: 10-10:SECONDS
#reconnections: 3
#reconnectionWait: 10-10:SECONDS
#proxy: null
#userAgent: null
#sleep: null